# Generated by Django 3.2.9 on 2021-12-14 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Benchmark', '0001_initial'),
        ('VideoLecture', '0001_initial'),
        ('WrittenLecture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now=True)),
                ('modify_time', models.TimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PathwayParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('on_pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='Paths.pathway')),
            ],
        ),
        migrations.CreateModel(
            name='PathwayContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('benchmark', 'Benchmark')], max_length=100)),
                ('order_position', models.PositiveIntegerField(default=9999)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now=True)),
                ('modify_time', models.TimeField(auto_now=True)),
                ('complete_to_move_on', models.BooleanField(default=True)),
                ('complete_anytime_overide', models.BooleanField(default=False)),
                ('revise_frequency', models.CharField(choices=[('Never', 'Never'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Never', max_length=100)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WrittenLecture.article')),
                ('benchmark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Benchmark.benchmark')),
                ('on_pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_pathway', to='Paths.pathway')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VideoLecture.videolecture')),
            ],
            options={
                'get_latest_by': 'order_position',
            },
        ),
        migrations.CreateModel(
            name='PathwayCompletitionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_record', to=settings.AUTH_USER_MODEL)),
                ('pathway_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paths.pathwaycontent')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pathwayparticipant',
            constraint=models.UniqueConstraint(fields=('on_pathway', 'author'), name='duplicate_pathway_participant'),
        ),
        migrations.AddConstraint(
            model_name='pathwaycontent',
            constraint=models.UniqueConstraint(fields=('on_pathway', 'order_position'), name='pathway_order_by'),
        ),
    ]
