# Generated by Django 3.2.5 on 2021-08-17 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='videolecture',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PathwayContentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('video-lecture', 'Video Lecture'), ('written-ecture', 'Video Lecture'), ('quiz', 'Knowledge Incrementer')], max_length=255)),
                ('order_by', models.PositiveIntegerField()),
                ('must_complete_previous', models.BooleanField()),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paths.pathway')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Paths.quiz')),
                ('video_lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Paths.videolecture')),
                ('written_lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Paths.writtenlecture')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='pathways',
            field=models.ManyToManyField(to='Paths.Pathway'),
        ),
        migrations.AddField(
            model_name='videolecture',
            name='pathways',
            field=models.ManyToManyField(to='Paths.Pathway'),
        ),
        migrations.AddField(
            model_name='writtenlecture',
            name='pathways',
            field=models.ManyToManyField(to='Paths.Pathway'),
        ),
        migrations.AddConstraint(
            model_name='pathwaycontentsetting',
            constraint=models.UniqueConstraint(fields=('pathway', 'order_by'), name='unique_order_by'),
        ),
    ]
