# Generated by Django 3.2.7 on 2021-11-24 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Paths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathwayParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('on_pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='Paths.pathway')),
            ],
        ),
        migrations.CreateModel(
            name='PathwayProgressionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_tracker', to='Paths.pathwayparticipant')),
            ],
        ),
    ]
