# Generated by Django 3.2.9 on 2022-01-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathwaycontent',
            options={'get_latest_by': 'order_position', 'ordering': ['order_position']},
        ),
    ]
