# Generated by Django 3.2.7 on 2021-11-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0002_pathwayparticipant_pathwayprogressiontracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PathwayProgressionTracker',
        ),
    ]
