# Generated by Django 3.2.5 on 2021-08-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0002_auto_20210817_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='pathways',
        ),
        migrations.RemoveField(
            model_name='videolecture',
            name='pathways',
        ),
        migrations.RemoveField(
            model_name='writtenlecture',
            name='pathways',
        ),
    ]
