# Generated by Django 3.2.9 on 2022-02-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0002_alter_pathwaycontent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathwayparticipant',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('active', 'active')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='pathway',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
