# Generated by Django 3.2.7 on 2021-11-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0004_pathwaycontent_benchmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathwaycontent',
            options={'get_latest_by': 'order_position'},
        ),
        migrations.AddConstraint(
            model_name='pathwayparticipant',
            constraint=models.UniqueConstraint(fields=('on_pathway', 'author'), name='duplicate_pathway_participant'),
        ),
    ]
