# Generated by Django 3.2.9 on 2022-02-02 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0004_auto_20220202_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathwayCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_quantity', models.PositiveIntegerField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_brackets', to='Paths.pathway')),
            ],
        ),
    ]
