# Generated by Django 3.2.7 on 2021-12-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0005_auto_20211129_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathwaycontent',
            old_name='revise_continuous',
            new_name='complete_to_move_on',
        ),
        migrations.RemoveField(
            model_name='pathwaycontent',
            name='complete_previous',
        ),
        migrations.AddField(
            model_name='pathwaycontent',
            name='complete_anytime_overide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pathwaycontent',
            name='revise_frequency',
            field=models.CharField(choices=[('Never', 'Never'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Never', max_length=100),
        ),
    ]
