# Generated by Django 3.2.9 on 2022-02-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0005_pathwaycost'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pathwaycost',
            constraint=models.UniqueConstraint(fields=('pathway', 'purchase_quantity'), name='duplicate_quantity_costs'),
        ),
    ]
