# Generated by Django 3.2.5 on 2021-08-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0006_alter_pathway_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathwaycontentsetting',
            name='content_type',
            field=models.CharField(choices=[('video-lecture', 'Video Lecture'), ('written-lecture', 'Written Lecture'), ('quiz', 'Knowledge Incrementer')], max_length=255),
        ),
    ]
