# Generated by Django 3.2.9 on 2022-02-04 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0006_pathwaycost_duplicate_quantity_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathwayparticipant',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Paths.pathwaypurchase'),
        ),
    ]
