# Generated by Django 3.2.9 on 2021-12-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0006_auto_20211201_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathwaycontent',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('benchmark', 'Benchmark')], max_length=100),
        ),
    ]
