# Generated by Django 3.2.5 on 2021-08-17 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0009_alter_videolecture_video_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathwayCompletitionRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(auto_now_add=True)),
                ('record_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='pathwaycontentsetting',
            name='is_refreshable',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='VideoLectureCompletionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_status', models.CharField(choices=[('first_completion', 'first_completion'), ('did_not_complete', 'did_not_complete'), ('recap_completion', 'recap_completion')], max_length=100)),
                ('pathway_to_complete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paths.pathwaycompletitionrecords')),
            ],
        ),
        migrations.AddField(
            model_name='pathwaycompletitionrecords',
            name='pathway_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paths.pathwaycontentsetting'),
        ),
    ]
