# Generated by Django 3.2.9 on 2022-02-05 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Paths', '0009_alter_pathwaypurchase_spent_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathwaypurchase',
            name='spent_on_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pathway_purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
