# Generated by Django 3.2.5 on 2021-08-17 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Paths', '0011_auto_20210817_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pathway_creator', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pathway',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='pathway_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
