# Generated by Django 3.2.5 on 2021-08-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0014_rename_is_refreshable_pathwaycontentsetting_must_revise_continous'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathwaycontentsetting',
            options={'get_latest_by': 'order_by'},
        ),
    ]
