# Generated by Django 3.2.6 on 2021-09-01 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Paths', '0015_alter_pathwaycontentsetting_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_date', models.DateField(auto_now_add=True)),
                ('generated_time', models.TimeField(auto_now_add=True)),
                ('source_type', models.CharField(choices=[('video-transcript', 'video-transcript'), ('written-lecture', 'written-lecture'), ('uploaded-document', 'uploaded-document')], max_length=255)),
                ('source_id', models.PositiveIntegerField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('user_proof', models.CharField(choices=[('perfect', 'perfect'), ('editable', 'editable'), ('incorrect', 'incorrect'), ('unknown', 'unknown')], max_length=255)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
