# Generated by Django 3.2.6 on 2021-09-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0016_generatedquestionbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedquestionbank',
            name='source_type',
            field=models.CharField(choices=[('transcript', 'transcript'), ('literature', 'literature'), ('document', 'document')], max_length=255),
        ),
        migrations.AlterField(
            model_name='generatedquestionbank',
            name='user_proof',
            field=models.CharField(choices=[('perfect', 'perfect'), ('editable', 'editable'), ('incorrect', 'incorrect'), ('unknown', 'unknown')], default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='answer_type',
            field=models.CharField(choices=[('multiple-choice', 'Multiple choice'), ('multiple-correct-choice', 'Multiple correct choices'), ('text-entry-exact', 'Text entry (Exact)'), ('text-entry-nearest', 'Text entry (Close enough)')], default='text-entry-exact', max_length=255),
        ),
    ]
