# Generated by Django 3.2.6 on 2021-09-10 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0017_auto_20210903_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='genereated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Paths.generatedquestionbank'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='to_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Paths.quizquestion'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='on_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Paths.quiz'),
        ),
    ]
