# Generated by Django 3.2.6 on 2021-09-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0019_quizanswer_genereated_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='has_been_modified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
