# Generated by Django 3.2.6 on 2021-09-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0020_quizquestion_has_been_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestion',
            old_name='genereated_from',
            new_name='generated_from',
        ),
    ]
