# Generated by Django 3.2.7 on 2021-09-30 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('source_type', models.CharField(choices=[('transcript', 'transcript'), ('article', 'article'), ('document', 'document')], max_length=255)),
                ('source_id', models.PositiveIntegerField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('user_proof', models.CharField(choices=[('perfect', 'perfect'), ('editable', 'editable'), ('incorrect', 'incorrect'), ('unknown', 'unknown'), ('trashed', 'trashed')], default='unknown', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
