# Generated by Django 3.2.7 on 2021-09-16 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_date', models.DateField(auto_now_add=True)),
                ('generated_time', models.TimeField(auto_now_add=True)),
                ('source_type', models.CharField(choices=[('transcript', 'transcript'), ('literature', 'literature'), ('document', 'document')], max_length=255)),
                ('source_id', models.PositiveIntegerField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('user_proof', models.CharField(choices=[('perfect', 'perfect'), ('editable', 'editable'), ('incorrect', 'incorrect'), ('unknown', 'unknown')], default='unknown', max_length=255)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
