# Generated by Django 3.2.7 on 2021-09-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionGenerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedquestionbank',
            name='user_proof',
            field=models.CharField(choices=[('perfect', 'perfect'), ('editable', 'editable'), ('incorrect', 'incorrect'), ('unknown', 'unknown'), ('trashed', 'trashed')], default='unknown', max_length=255),
        ),
    ]
