# Generated by Django 3.2.5 on 2021-08-09 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0003_memberprofile_week_reset_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='month_reset_day',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
