# Generated by Django 3.2.5 on 2021-08-09 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0004_memberprofile_month_reset_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='year_reset_month',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
