# Generated by Django 3.2.5 on 2021-08-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0003_auto_20210817_1010'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pathwaycontentsetting',
            name='unique_order_by',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='body',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='order_by',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='pathwaycontentsetting',
            constraint=models.UniqueConstraint(fields=('pathway', 'order_by'), name='pathway_order_by'),
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.UniqueConstraint(fields=('on_quiz', 'order_by'), name='question_order_by'),
        ),
    ]
