# Generated by Django 3.2.5 on 2021-08-17 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Paths', '0004_auto_20210817_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pathwaycontentsetting',
            name='content_type',
            field=models.CharField(choices=[('video-lecture', 'Video Lecture'), ('written-ecture', 'Written Lecture'), ('quiz', 'Knowledge Incrementer')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pathwaycontentsetting',
            name='pathway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_pathway', to='Paths.pathway'),
        ),
    ]
