# Generated by Django 3.2.5 on 2021-08-17 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Paths', '0005_auto_20210817_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathway',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
