# Generated by Django 3.2.5 on 2021-08-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0010_auto_20210817_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolecture',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WrittenLectureCompletionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_status', models.CharField(choices=[('first_completion', 'first_completion'), ('did_not_complete', 'did_not_complete'), ('recap_completion', 'recap_completion')], max_length=100)),
                ('pathway_to_complete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paths.pathwaycompletitionrecords')),
            ],
        ),
        migrations.CreateModel(
            name='QuizLectureCompletionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_status', models.CharField(choices=[('first_completion', 'first_completion'), ('did_not_complete', 'did_not_complete'), ('recap_completion', 'recap_completion')], max_length=100)),
                ('pathway_to_complete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paths.pathwaycompletitionrecords')),
            ],
        ),
    ]
