# Generated by Django 3.2.5 on 2021-08-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0012_auto_20210817_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
