# Generated by Django 3.2.5 on 2021-08-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paths', '0013_pathway_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathwaycontentsetting',
            old_name='is_refreshable',
            new_name='must_revise_continous',
        ),
    ]
