# Generated by Django 3.2.9 on 2022-01-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoLecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolecture',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
