# Generated by Django 3.2.7 on 2021-09-30 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WebsiteTools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('motivation', models.TextField(blank=True, null=True)),
                ('user_status', models.CharField(choices=[('deleted', 'deleted'), ('active', 'active'), ('inactive', 'inactive'), ('completed', 'completed')], default='active', max_length=100)),
                ('order_position', models.PositiveIntegerField(default=9999)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('create_time', models.TimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebsiteTools.contentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Behaviour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('user_status', models.CharField(choices=[('deleted', 'deleted'), ('active', 'active'), ('inactive', 'inactive'), ('completed', 'completed')], default='active', max_length=100)),
                ('order_position', models.PositiveIntegerField()),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('create_time', models.TimeField(auto_now_add=True, null=True)),
                ('on_aim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Development.aim')),
            ],
        ),
        migrations.CreateModel(
            name='StepTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_tracker_type', models.CharField(choices=[('maximize', 'Count Up'), ('minimize', 'Count Down'), ('boolean', 'Yes or No')], max_length=100)),
                ('metric_action', models.TextField(blank=True, null=True)),
                ('metric_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('metric_int_only', models.BooleanField(blank=True, null=True)),
                ('metric_min', models.FloatField(blank=True, null=True)),
                ('metric_max', models.FloatField(blank=True, null=True)),
                ('minimum_show_allowed', models.BooleanField(blank=True, null=True)),
                ('minimum_show_description', models.TextField(blank=True, null=True)),
                ('record_start_date', models.DateField()),
                ('record_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Specific days')], max_length=100)),
                ('record_multiple_per_frequency', models.BooleanField()),
                ('complete_allowed', models.BooleanField(default=True)),
                ('complete_criteria', models.CharField(choices=[('consecutive', 'consecutive'), ('total', 'total')], default='consecutive', max_length=100)),
                ('complete_value', models.PositiveIntegerField()),
                ('user_status', models.CharField(choices=[('deleted', 'deleted'), ('active', 'active'), ('inactive', 'inactive'), ('completed', 'completed')], default='active', max_length=100)),
                ('order_position', models.PositiveIntegerField(default=9999)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('on_behaviour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='Development.behaviour')),
            ],
        ),
        migrations.CreateModel(
            name='StepTrackerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('submit_type', models.CharField(choices=[('count_showup', 'count show up'), ('count_value', 'count submit'), ('boolean_showup', 'boolean show up'), ('boolean_success', 'boolean complete'), ('fail_or_no_submit', 'fail or no submit')], max_length=100)),
                ('count_value', models.FloatField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('on_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_logs', to='Development.steptracker')),
            ],
        ),
        migrations.CreateModel(
            name='StepTrackerCustomFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('Day repeat', (('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wendnesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'))), ('Day of month repeat', (('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18), ('19', 19), ('20', 20), ('21', 21), ('22', 22), ('23', 23), ('24', 24), ('25', 25), ('26', 26), ('27', 27), ('28', 28), ('29', 29), ('30', 30), ('31', 31))), ('Month of year repeat', (('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')))], max_length=100)),
                ('on_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Development.steptracker')),
            ],
        ),
        migrations.AddConstraint(
            model_name='steptracker',
            constraint=models.UniqueConstraint(fields=('on_behaviour', 'order_position'), name='unique_order_of_trackers'),
        ),
        migrations.AddConstraint(
            model_name='behaviour',
            constraint=models.UniqueConstraint(fields=('on_aim', 'order_position'), name='unique_order_of_behaviours'),
        ),
        migrations.AddConstraint(
            model_name='aim',
            constraint=models.UniqueConstraint(fields=('author', 'order_position'), name='unique_order_of_aims'),
        ),
    ]
