# Generated by Django 3.2.9 on 2022-02-13 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aim',
            name='is_a_copy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='behaviour',
            name='is_a_copy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='steptracker',
            name='is_a_copy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='behaviour',
            name='on_aim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviours', to='Development.aim'),
        ),
    ]
