# Generated by Django 3.2.7 on 2021-09-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptracker',
            name='metric_number_display_type',
            field=models.CharField(choices=[('float', 'Upto 2 decimal places'), ('integer', 'Whole number only')], default='float', max_length=100),
        ),
        migrations.AlterField(
            model_name='steptracker',
            name='order_position',
            field=models.PositiveIntegerField(default=9999),
        ),
        migrations.AlterField(
            model_name='steptracker',
            name='record_start_date',
            field=models.TimeField(),
        ),
    ]
