# Generated by Django 3.2.7 on 2021-09-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptracker',
            name='complete_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='steptracker',
            name='complete_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
