# Generated by Django 3.2.7 on 2021-09-20 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillArea',
        ),
    ]
