# Generated by Django 3.2.7 on 2021-09-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0002_delete_skillarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='aim',
            name='publish_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='aim',
            name='publish_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
