# Generated by Django 3.2.7 on 2021-09-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0003_auto_20210927_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aim',
            old_name='publish_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='aim',
            old_name='publish_time',
            new_name='create_time',
        ),
    ]
