# Generated by Django 3.2.7 on 2021-10-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0003_auto_20210930_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='steptracker',
            name='record_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='steptrackerlog',
            name='submit_type',
            field=models.CharField(choices=[('count_showup', 'count show up'), ('count_value', 'count submit'), ('boolean_showup', 'boolean show up'), ('boolean_success', 'boolean complete'), ('fail_or_no_submit', 'did not complete')], max_length=100),
        ),
    ]
