# Generated by Django 3.2.7 on 2021-10-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0004_auto_20211004_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptracker',
            name='record_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Specific days or months')], default='weekly', max_length=100),
        ),
        migrations.AlterField(
            model_name='steptrackerlog',
            name='submit_type',
            field=models.CharField(choices=[('min_showup', 'minimum show'), ('count_value', 'count submit'), ('boolean_success', 'boolean complete'), ('fail_or_no_submit', 'did not complete')], max_length=100),
        ),
    ]
