# Generated by Django 3.2.7 on 2021-10-19 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0005_auto_20211008_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptrackerlog',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='steptrackerlog',
            name='create_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
