# Generated by Django 3.2.7 on 2021-09-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0005_auto_20210929_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptracker',
            name='metric_int_only',
            field=models.BooleanField(),
        ),
    ]
