# Generated by Django 3.2.6 on 2021-08-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0005_auto_20210826_1637'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aim',
            name='unique_aims_orderby',
        ),
        migrations.AlterField(
            model_name='aim',
            name='in_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
