# Generated by Django 3.2.6 on 2021-08-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0006_auto_20210827_1102'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lever',
            name='unique order of levers',
        ),
        migrations.AlterField(
            model_name='aim',
            name='in_order',
            field=models.PositiveIntegerField(default=9999),
        ),
        migrations.AddConstraint(
            model_name='aim',
            constraint=models.UniqueConstraint(fields=('user', 'in_order'), name='unique_aims_orderby'),
        ),
        migrations.AddConstraint(
            model_name='lever',
            constraint=models.UniqueConstraint(fields=('on_aim', 'in_order'), name='unique_order_of_levers'),
        ),
    ]
