# Generated by Django 3.2.7 on 2021-10-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0007_auto_20211021_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptracker',
            name='record_frequency',
            field=models.CharField(choices=[('daily', 'Every day'), ('weekly', 'Every week'), ('monthly', 'Every month'), ('yearly', 'Every year'), ('custom', 'Specific days, weeks or months')], default='weekly', max_length=100),
        ),
        migrations.AlterField(
            model_name='steptracker',
            name='record_log_length',
            field=models.CharField(choices=[('day', 'A day'), ('week', 'A week'), ('month', 'A month'), ('year', 'A year')], default='day', max_length=100),
        ),
    ]
