# Generated by Django 3.2.6 on 2021-08-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0007_auto_20210827_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lever',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skillarea',
            name='forum_rules',
            field=models.TextField(),
        ),
    ]
