# Generated by Django 3.2.7 on 2021-09-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0007_rename_complete_endpoint_steptracker_complete_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptracker',
            name='metric_int_only',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='steptracker',
            name='metric_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='steptracker',
            name='metric_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='steptracker',
            name='minimum_show_allowed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
