# Generated by Django 3.2.7 on 2021-09-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0008_auto_20210929_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptracker',
            name='metric_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
