# Generated by Django 3.2.9 on 2021-12-06 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0008_auto_20211026_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='steptrackerlog',
            name='create_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
