# Generated by Django 3.2.7 on 2021-09-29 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Development', '0009_alter_steptracker_metric_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepTrackerLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('submit_type', models.CharField(choices=[('no_submit', 'no submit'), ('count_showup', 'count show up'), ('count_value', 'count submit')], max_length=100)),
                ('count_value', models.FloatField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('on_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_logs', to='Development.steptracker')),
            ],
        ),
    ]
