# Generated by Django 3.2.9 on 2021-12-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0009_steptrackerlog_create_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steptrackerlog',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='steptrackerlog',
            name='create_time',
        ),
    ]
