# Generated by Django 3.2.9 on 2021-12-14 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0011_alter_steptrackerlog_create_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptrackerlog',
            name='create_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
