# Generated by Django 3.2.7 on 2021-09-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShareContent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreatedgroupcontent',
            name='assigned_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_pathways', to='ShareContent.usercreatedgroup'),
        ),
    ]
