# Generated by Django 3.2.5 on 2021-07-22 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('why', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lever',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='A description of the lever you will pull')),
                ('in_order', models.IntegerField()),
                ('on_aim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Development.aim')),
            ],
        ),
        migrations.CreateModel(
            name='TrackerMinAim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('mins', 'Minutes'), ('hours', 'Hours'), ('repititions', 'Repititions')], max_length=100)),
                ('metric_min', models.IntegerField()),
                ('metric_aim', models.IntegerField()),
                ('metric_description', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly'), ('year', 'Yearly'), ('custom', 'Custom')], max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('lever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_min_aim', to='Development.lever')),
            ],
        ),
        migrations.CreateModel(
            name='SkillArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_area_name', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('forum_rules', models.TextField(default='The forum rules for this skill area are..')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MinAimRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lever_performed', models.BooleanField()),
                ('record_date', models.DateField(auto_now_add=True)),
                ('record_time', models.TimeField(auto_now_add=True)),
                ('metric_quantity', models.IntegerField(blank=True, null=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Development.trackerminaim')),
            ],
        ),
        migrations.CreateModel(
            name='DevelopmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Development.developmentcategory')),
            ],
        ),
        migrations.AddField(
            model_name='aim',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Development.developmentcategory'),
        ),
        migrations.AddField(
            model_name='aim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='lever',
            constraint=models.UniqueConstraint(fields=('on_aim', 'in_order'), name='unique order of levers'),
        ),
    ]
