# Generated by Django 3.2.5 on 2021-08-11 10:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackerminaim',
            name='day_reset_on',
        ),
        migrations.RemoveField(
            model_name='trackerminaim',
            name='week_reset_on',
        ),
        migrations.CreateModel(
            name='TrackerBooleanRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lever_performed', models.BooleanField()),
                ('record_date', models.DateField(auto_now_add=True)),
                ('record_time', models.TimeField(auto_now_add=True)),
                ('metric_quantity', models.BooleanField()),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Development.trackerminaim')),
            ],
        ),
        migrations.CreateModel(
            name='TrackerBoolean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_description', models.TextField(max_length=500)),
                ('frequency', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], max_length=100)),
                ('frequency_quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('complete_criteria', models.CharField(choices=[('consecutive', 'consecutive'), ('total', 'total')], max_length=100)),
                ('complete_value', models.PositiveIntegerField()),
                ('has_prompt', models.BooleanField(default=True)),
                ('has_timeout', models.BooleanField(default=True)),
                ('has_public_logs', models.BooleanField(default=False)),
                ('allows_multi_period_logs', models.BooleanField(default=True)),
                ('lever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_boolean', to='Development.lever')),
            ],
        ),
    ]
