# Generated by Django 3.2.5 on 2021-07-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lever',
            name='in_order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trackerminaim',
            name='metric_type',
            field=models.CharField(max_length=100),
        ),
    ]
