# Generated by Django 3.2.5 on 2021-08-11 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0002_auto_20210811_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentcategory',
            name='global_standard',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trackerbooleanrecords',
            name='metric_quantity',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default='Yes'),
        ),
        migrations.AlterField(
            model_name='trackerbooleanrecords',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Development.trackerboolean'),
        ),
    ]
