# Generated by Django 3.2.5 on 2021-07-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0002_auto_20210723_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerminaim',
            name='complete_criteria',
            field=models.CharField(choices=[('Consecutive', 'Consecutive'), ('Total', 'Total')], default='Total', max_length=100),
        ),
        migrations.AddField(
            model_name='trackerminaim',
            name='complete_value',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trackerminaim',
            name='frequency',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('6 of 7 Days', '6 of 7 Days'), ('5 of 7 Days', '5 of 7 Days'), ('4 of 7 Days', '4 of 7 Days'), ('3 of 7 Days', '3 of 7 Days'), ('2 of 7 Days', '2 of 7 Days'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=100),
        ),
        migrations.AlterField(
            model_name='trackerminaim',
            name='metric_aim',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trackerminaim',
            name='metric_min',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
