# Generated by Django 3.2.5 on 2021-07-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0002_trackerminaim_week_reset_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerminaim',
            name='day_reset_on',
            field=models.CharField(choices=[('midnight', 'midnight'), ('sleep setting', 'your sleep setting')], default='midnight', max_length=100),
        ),
        migrations.AlterField(
            model_name='trackerminaim',
            name='week_reset_on',
            field=models.CharField(choices=[('start date day', 'The day of the week you start your tracker'), ('members profile', 'The day set on your user profile')], default='start date day', max_length=100),
        ),
    ]
