# Generated by Django 3.2.5 on 2021-08-08 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0003_auto_20210729_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerminaim',
            name='frequency_quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
