# Generated by Django 3.2.5 on 2021-08-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Development', '0004_trackerminaim_frequency_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerminaim',
            name='frequency',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], max_length=100),
        ),
    ]
