# Generated by Django 3.2.9 on 2022-01-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WrittenLecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
