# Generated by Django 3.2.9 on 2022-01-29 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WrittenLecture', '0003_alter_article_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('recap', 'recap'), ('complete', 'complete'), ('incomplete', 'incomplete')], max_length=100)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('completion_time', models.PositiveIntegerField()),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_sessions', to=settings.AUTH_USER_MODEL)),
                ('on_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WrittenLecture.article')),
            ],
        ),
    ]
