# Generated by Django 3.2.9 on 2022-01-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WrittenLecture', '0004_articlesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesession',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('recap', 'recap'), ('complete', 'complete'), ('incomplete', 'incomplete')], default='pending', max_length=100),
        ),
    ]
