# Generated by Django 3.2.9 on 2022-02-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WrittenLecture', '0005_alter_articlesession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(default='There is no description for this article', max_length=500),
        ),
    ]
