# Generated by Django 3.2.7 on 2021-11-24 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationContentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_content', to='Organisations.organisationcontent')),
                ('participants', models.ManyToManyField(related_name='tracker_participants', to=settings.AUTH_USER_MODEL)),
                ('tracked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_trackers', to='Organisations.organisation')),
            ],
        ),
    ]
