# Generated by Django 3.2.7 on 2021-11-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisations', '0002_organisationcontenttracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='force_parent_member',
            field=models.BooleanField(default=True),
        ),
    ]
