# Generated by Django 3.2.9 on 2022-01-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organisations', '0003_auto_20220112_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='members',
        ),
    ]
