# Generated by Django 3.2.9 on 2022-01-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organisations', '0007_auto_20220112_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationmembers',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_members', to='Organisations.organisation'),
        ),
    ]
