# Generated by Django 3.2.9 on 2022-02-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisations', '0008_alter_organisationmembers_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='description',
            field=models.TextField(default='There is no description set for this organisation'),
        ),
    ]
