# Generated by Django 3.1.2 on 2021-06-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='skill_area',
            field=models.CharField(default='None set', max_length=255),
        ),
    ]
