# Generated by Django 3.2.5 on 2021-07-06 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='modify_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='modify_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='modify_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='modify_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='on_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.post'),
        ),
    ]
