# Generated by Django 3.2.5 on 2021-08-13 07:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(default='"The First Key To Writing Is To Write… Not To Think. You Write Your First Draft With Your Heart, Your Rewrite, With Your Head".'),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic_snippet',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
