# Generated by Django 3.2.5 on 2021-07-05 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='on_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_comments', to='forum.post'),
        ),
    ]
